<?php

namespace App\Services;

use App\Repositories\UserRepository;

class UserService extends CustomService
{
    public function __construct()
    {
        parent::__construct();
        $this->setRepository(app(UserRepository::class));
    }

    public function store($params)
    {
        return parent::store($params); // TODO: Change the autogenerated stub
    }

    public function update($id, $params)
    {
        return parent::update($id, $params); // TODO: Change the autogenerated stub
    }

    public function destroy($id)
    {
        return parent::destroy($id); // TODO: Change the autogenerated stub
    }
}
